import {
	FormControl,
	InputLabel,
	MenuItem,
	Select,
	TextField,
} from '@material-ui/core'
import Axios from 'axios'
import React, { useEffect, useState } from 'react'
import { useRecoilState } from 'recoil'
import styled from 'styled-components'
import Controls from '../../../components/Controls'
import { roleAtom } from '../../../recoil/atoms'
import {
	ControlButton,
	ContentContainer,
	Card,
	StyledCheckbox,
	RemoveSpaces,
} from '../../../styles'
import { userEndpoint, rolesEndpoint } from '../../../api'
import passwordGenerator from 'generate-password'
import { encryptObj } from '../../../utils/helperFunctions'
import {
	SMUIFormControl,
	SMUISelect,
	SMUITextField,
} from '../../../styles/StyledMaterialUI'

//------------

function UserInput() {
	const [roles, setRoles] = useRecoilState(roleAtom)
	const [roleId, setRoleId] = useState('')

	const [firstName, setFirstName] = useState('')
	const [lastName, setLastName] = useState('')
	const [userName, setUserName] = useState('')
	const [email, setEmail] = useState('')
	const [password, setPassword] = useState('')
	const [contact, setContact] = useState('')
	const [isAutoGenerated, setIsAutoGenerated] = useState('')

	useEffect(() => {
		Axios.get(rolesEndpoint)
			.then(({ data }) => setRoles(data))
			.catch((e) => console.log(e))
	}, [])

	const saveUserHandler = async () => {
		const userData = {
			firstName,
			lastName,
			userName,
			password,
			email,
			contact,
			roleId,
		}
		const data = encryptObj(userData)

		try {
			await Axios.post(userEndpoint, { data })
		} catch (error) {
			console.log(error)
		}
	}

	const autoGeneratePassword = (e) => {
		const checked = e.target.checked

		setIsAutoGenerated(checked)
		if (checked) {
			const password = passwordGenerator.generate({
				length: 12,
				numbers: true,
				symbols: true,
				excludeSimilarCharacters: true,
			})
			setPassword(password)
		}
	}
	return (
		<>
			<Controls title='Add User'>
				<ControlButton color='secondary'>Reset</ControlButton>
				<ControlButton
					onClick={saveUserHandler}
					variant='contained'
					color='primary'>
					Save
				</ControlButton>
			</Controls>
			<ContentContainer>
				<Card>
					<SMUIFormControl>
						<InputLabel id='role'>Role</InputLabel>
						<SMUISelect
							labelId='role'
							value={roleId}
							onChange={(e) => setRoleId(e.target.value)}>
							{roles &&
								roles.map((role) => {
									return <MenuItem value={role._id}>{role.name}</MenuItem>
								})}
						</SMUISelect>
					</SMUIFormControl>
					<SMUITextField
						value={email}
						onChange={(e) => setEmail(e.target.value)}
						type='email'
						label='Email'
					/>
					<SMUITextField
						disabled={isAutoGenerated}
						value={password}
						onChange={(e) => setPassword(e.target.value)}
						type='text'
						label='Password'
					/>
					<AutoGeneratorPassContainer>
						<StyledCheckbox
							checked={isAutoGenerated}
							onChange={autoGeneratePassword}
							type='checkbox'
						/>
						<AutoGeneratorLabel>Auto Generated</AutoGeneratorLabel>
					</AutoGeneratorPassContainer>
					<SMUITextField
						value={firstName}
						onChange={(e) => setFirstName(e.target.value)}
						label='First Name'
					/>
					<SMUITextField
						value={lastName}
						onChange={(e) => setLastName(e.target.value)}
						label='Last Name'
					/>
					<SMUITextField
						value={userName}
						onChange={(e) => setUserName(e.target.value)}
						label='Username'
					/>
					<SMUITextField
						value={contact}
						onChange={(e) => setContact(e.target.value)}
						type='number'
						label='Contact No.'
					/>
				</Card>
			</ContentContainer>
		</>
	)
}

export default UserInput

const UserTextField = styled(TextField)`
	&& {
		width: 100%;
		margin: 6px 0px;
	}
`
const UserRoleSelect = styled(Select)`
	&& {
		width: 100%;
		text-align: left;
	}
`
const AutoGeneratorPassContainer = styled.div`
	display: flex;
	justify-content: flex-start;
	align-items: center;
`

const AutoGeneratorLabel = styled.p`
	${RemoveSpaces};
	padding-left: 5px;
	font-size: 0.8em;
	font-weight: 400;
`
